### ISSUE TITLE
Extra Opher upgrades

### ISSUE THREAD

**Issue by MunWolf** [sparkle-preference/OriWotwRandomizerClient#71]
At some point we mentioned adding more upgrades for Opher and randomize which ones were available (possibly adding the excess ones to the pickup pool)

This issue is to keep track of upgrades we want to add, other upgrades will be added to this list and crossed out as they are added.

- [x] Hammer Speed
- [x] Sword Speed
- [x] Energy Efficency
- [x] Blaze melts ice
- [x] Bash off uncharged grenades (might be way too strong?)
- [x] Spear attack/charge speed

EDIT: This is just the ability to make these upgrades in headers, they don't necessarily have to be used.

**Comment by MunWolf** [comment]
Done
